- name: Install apache2 and support packages
  tags: apache,apache2,ubuntu
  apt:
    update_cache: yes
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"




- name: Install apache2 and support packages
  tags: apache,httpd,oracleLinux
  dnf:
    update_cache: yes
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "OracleLinux"


- name: Copy default html file to sites
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: 0644

